[package]
name = "speakrs"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.12.1"
clap = { version = "4.6.4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tarpc = { version = "0.37.0", features = ["full"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"]}
anyhow = "1.0.104"
speakrs-gui = { path = "crates/speakrs-gui" }
sled = "0.34.7"
uuid = { version = "1.24.0", features = ["serde", "v4", "v7", "bytemuck"] }
bytemuck = { version = "1.25.2", features = ["derive"] }
rkyv = { version = "0.8.17", features = ["uuid-1"] }
chrono = { version = "0.4.45", features = ["rkyv", "serde", "rkyv-validation"] }

[workspace]
members = [".", "crates/speakrs-gui"]

