use crate::common::key::generator::GenerateKey;

/// All potential shapes for `tree.insert` argument.
pub trait DbInsertable<K, V, Gen>: Sized {
    type Return;
    fn execute_insert<E>(
        &self,
        generator: &Gen,
        do_insert_entry: impl Fn(&K, &V) -> Result<(), E>,
    ) -> Result<Self::Return, E>;
}

// Implementation for direct key,value pair insertion.
impl<K, V, Gen> DbInsertable<K, V, Gen> for (K, V) {
    type Return = ();
    fn execute_insert<E>(
        &self,
        _generator: &Gen,
        do_insert_entry: impl Fn(&K, &V) -> Result<(), E>,
    ) -> Result<Self::Return, E> {
        do_insert_entry(&self.0, &self.1)
    }
}

// Implementation for value insertion with autogenerated key.
impl<K, V, Gen: GenerateKey<K>> DbInsertable<K, V, Gen> for V {
    type Return = K;
    fn execute_insert<E>(
        &self,
        generator: &Gen,
        do_insert_entry: impl Fn(&K, &V) -> Result<(), E>,
    ) -> Result<Self::Return, E> {
        let key = generator.generate_next();
        do_insert_entry(&key, &self)?;
        Ok(key)
    }
}

impl<const N: usize, K, V, Gen: GenerateKey<K>> DbInsertable<K, V, Gen> for [V; N] {
    type Return = [K; N];

    fn execute_insert<E>(
        &self,
        generator: &Gen,
        do_insert_entry: impl Fn(&K, &V) -> Result<(), E>,
    ) -> Result<Self::Return, E> {
        let keys = std::array::from_fn(|_| generator.generate_next());
        keys.as_slice()
            .iter()
            .zip(self.as_slice())
            .try_for_each(|(k, v)| do_insert_entry(k, v))?;
        Ok(keys)
    }
}

impl<const N: usize, K, V, Gen> DbInsertable<K, V, Gen> for [(K, V); N] {
    type Return = ();

    fn execute_insert<E>(
        &self,
        _generator: &Gen,
        do_insert_entry: impl Fn(&K, &V) -> Result<(), E>,
    ) -> Result<Self::Return, E> {
        for (k, v) in self {
            do_insert_entry(k, v)?;
        }
        Ok(())
    }
}

impl<K, V, Gen: GenerateKey<K>> DbInsertable<K, V, Gen> for &[V]
where
    V: DbInsertable<K, V, Gen>,
{
    type Return = Vec<V::Return>;

    fn execute_insert<E>(
        &self,
        generator: &Gen,
        do_insert_entry: impl Fn(&K, &V) -> Result<(), E>,
    ) -> Result<Self::Return, E> {
        Ok(self
            .into_iter()
            .map(move |v| v.execute_insert(generator, &do_insert_entry))
            .collect::<Result<_, _>>()?)
    }
}
