use std::{net::{IpAddr, Ipv6Addr, SocketAddr}, sync::{Arc, Mutex}};

use tarpc::{context::Context, server::{Channel, incoming::Incoming}, tokio_serde::formats::Json};

use crate::common::{self, ChannelId, Message, MessageId, ServerResult, UserId, World};

use futures::{future, prelude::*};

#[derive(Debug, clap::Parser)]
pub(crate) struct ServerArguments {
    /// Port to serve tcp commands under
    #[clap(short, long)]
    port: u16,
}

pub(crate) async fn run(args: ServerArguments) -> anyhow::Result<()> {
    let server = ServerData::new();
    command_server(args, server.clone()).await
}

// This is the type that implements the generated World trait. It is the business logic
// and is used to start the server.
#[derive(Clone)]
struct HelloServer(SocketAddr, ServerData);

impl common::World for HelloServer {
    async fn hello(self, _: Context, name: String) -> String {
        // let sleep_time =
        //     Duration::from_millis(Uniform::new_inclusive(1, 10).unwrap().sample(&mut rand::rng()));
        // tokio::time::sleep(sleep_time).await;
        format!("Hello, {name}! You are connected from {}", self.0)
    }

    async fn pull_messages(self, context: Context, channel_id: ChannelId, limit: usize) -> ServerResult<Vec<Message>>  {
        let data = self.1;
        let x = data.db.lock().unwrap();
        x.pull_messages(channel_id, limit)
    }

    async fn send_message(self, context: Context, channel_id: ChannelId, user: UserId, content: String) -> ServerResult<MessageId>  {
        let data = self.1;
        let mut x = data.db.lock().unwrap();
        x.send_message(channel_id, user, content)
    }

}

async fn spawn(fut: impl Future<Output = ()> + Send + 'static) {
    tokio::spawn(fut);
}

#[tracing::instrument]
async fn command_server(args: ServerArguments, server: ServerData) -> anyhow::Result<()> {
   let server_addr = (IpAddr::V6(Ipv6Addr::LOCALHOST), args.port);
   let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Json::default).await?;
   tracing::info!("Listening on port {}", listener.local_addr().port());
   listener.config_mut().max_frame_length(usize::MAX);
   listener
   // Ignore accept errors.
       .filter_map(|r| future::ready(r.ok()))
       .map(tarpc::server::BaseChannel::with_defaults)
   // Limit channels to 1 per IP.
       .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
   // serve is generated by the service attribute. It takes as input any type implementing
   // the generated World trait.
       .map(|channel| {
           let server = HelloServer(channel.transport().peer_addr().unwrap(), server.clone());
           channel.execute(server.serve()).for_each(spawn)
       })
   // Max 10 channels.
       .buffer_unordered(10)
       .for_each(|_| async {})
       .await;

    Ok(())
}


// ==============================
// => Server Data
// ==============================

#[derive(Clone, Debug)]
struct ServerData {
    db: Arc<Mutex<common::Server>>,
}

impl ServerData {
    fn new() -> Self {
        let db = Arc::new(Mutex::new(common::Server::new()));
        Self {
            db
        }
    }

    fn lock_db(&mut self) -> Result<std::sync::MutexGuard<'_, common::Server>, std::sync::PoisonError<std::sync::MutexGuard<'_, common::Server>>> {
        self.db.lock()
    }
}
