use std::{net::{IpAddr, Ipv6Addr, SocketAddr}, sync::{Arc, Mutex}};

use tarpc::{context::Context, server::{Channel, incoming::Incoming}, tokio_serde::formats::Json};

use crate::common::{self, ChannelData, ChannelKey, MessageData, MessageKey, ServerDB, UserData, UserKey, World};

use futures::{future, prelude::*};

#[derive(Debug, clap::Parser)]
pub(crate) struct ServerArguments {
    /// Port to serve tcp commands under
    #[clap(short, long)]
    port: u16,
}

pub(crate) async fn run(args: ServerArguments) -> anyhow::Result<()> {
    let server = ServerDB::new("test.db");
    let user_key = UserKey::default();
    let user1 = UserData::new("user_1".to_string());
    server.users()?.insert(user_key, user1)?;
    println!("inserted user1");
    let channel_key = ChannelKey::default();
    let channel1 = ChannelData::text("Channel 1".to_string(), "An example channel".to_string());
    server.channels()?.insert(channel_key, channel1)?;
    println!("inserted channel1");
    let message1 = MessageData::now(user_key, "Test Message 1".to_string());
    let message_key = MessageKey::with_channel(channel_key);
    server.messages()?.insert(message_key, message1)?;
    println!("inserted message1");

    println!("reading data");
    println!();

    let got_channel = server.channels()?.get(channel_key)?.expect("Expected channel that was just inserted");
    let got_message1 = server.messages()?.get(message_key)?.expect("Expected message value that was just inserted");
    let message_user_key = got_message1.author;
    let got_user = server.users()?.get(message_user_key)?.expect("Expected user value that was just inserted");
    println!("Had message: @\"{}\" <{}> {}: {}", got_channel.get_name(), got_message1.timestamp, got_user.name, got_message1.content);
    Ok(())
    //command_server(args, server).await
}

// This is the type that implements the generated World trait. It is the business logic
// and is used to start the server.
#[derive(Clone)]
struct HelloServer(SocketAddr, ServerDB);

impl common::World for HelloServer {
async fn hello(self, _: Context, name: String) -> String {
    // let sleep_time =
    //     Duration::from_millis(Uniform::new_inclusive(1, 10).unwrap().sample(&mut rand::rng()));
    // tokio::time::sleep(sleep_time).await;
    format!("Hello, {name}! You are connected from {}", self.0)
}

// async fn pull_messages(self, context: Context, channel_id: ChannelKey, limit: usize) -> ServerResult<Vec<MessageData>>  {
    //     let data = self.1;
    //     let x = data.db.lock().unwrap();
    //     x.pull_messages(channel_id, limit)
    // }

    // async fn send_message(self, context: Context, channel_id: ChannelKey, user: UserKey, content: String) -> ServerResult<MessageKey>  {
    //     let data = self.1;
    //     let mut x = data.db.lock().unwrap();
    //     x.send_message(channel_id, user, content)
    // }

}

async fn spawn(fut: impl Future<Output = ()> + Send + 'static) {
    tokio::spawn(fut);
}

#[tracing::instrument]
async fn command_server(args: ServerArguments, server: ServerDB) -> anyhow::Result<()> {
   let server_addr = (IpAddr::V6(Ipv6Addr::LOCALHOST), args.port);
   let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Json::default).await?;
   tracing::info!("Listening on port {}", listener.local_addr().port());
   listener.config_mut().max_frame_length(usize::MAX);
   listener
   // Ignore accept errors.
       .filter_map(|r| future::ready(r.ok()))
       .map(tarpc::server::BaseChannel::with_defaults)
   // Limit channels to 1 per IP.
       .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
   // serve is generated by the service attribute. It takes as input any type implementing
   // the generated World trait.
       .map(|channel| {
           let server = HelloServer(channel.transport().peer_addr().unwrap(), server.clone());
           channel.execute(server.serve()).for_each(spawn)
       })
   // Max 10 channels.
       .buffer_unordered(10)
       .for_each(|_| async {})
       .await;

    Ok(())
}
