use std::{
    net::{IpAddr, Ipv6Addr, SocketAddr},
    path::PathBuf,
};

use tarpc::{
    context::Context,
    server::{Channel, incoming::Incoming},
    tokio_serde::formats::Json,
};

use crate::common::{self, database::ServerDB, rpc::RpcService};

use futures::{future, prelude::*};

#[derive(Debug, clap::Parser)]
pub(crate) struct ServerArguments {
    // TODO: reconsider port
    /// Port to serve tcp commands under (default: 57112)
    #[clap(short, long, default_value_t = 57112)]
    port: u16,
    // TODO: wording may be bad: ;; also write a manual
    /// name of the server, this will determine where to store server database, it should be unique in any given system.
    /// Clients will use the internal uuid of the server not the name, so a client can connect with multiple servers of the same name.
    /// On the same system only one server can exist with this name.
    ///
    /// If no name is provided, uses "default_server".
    ///
    /// If unsure consult the manual.
    #[clap(short, long, default_value_t="default_server".to_string())]
    name: String,
}

pub(crate) async fn run(args: ServerArguments) -> anyhow::Result<()> {
    let server = ServerDB::magic_open_server(args.name.to_string())?;
    command_server(args, server).await?;
    Ok(())
}

// ======================================
// => Server Config
// ======================================
// NOTE: For Devs: Try to annotate every value with `///` and explain what it does
#[derive(Clone, serde::Deserialize, serde::Serialize)]
pub struct ServerConfig {
    /// Database related settings
    database: ServerConfigDatabase,
}
#[derive(Clone, serde::Deserialize, serde::Serialize)]
pub struct ServerConfigDatabase {
    /// Directory to store server databases in, if empty stores databases next to config.
    /// If set to `/some/dir` creates `/some/dir/server` and `/some/dir/server/<server_name>` for each database
    directory: Option<String>,
}
impl ServerConfig {
    /// See [`ServerConfig::database`]
    pub fn get_database_directory(&self) -> PathBuf {
        if self.database.directory.is_some() {
            return PathBuf::from(self.database.directory.clone().unwrap());
        }
        let mut path = common::config_home();
        path.push("databases");
        path.push("server");
        path
    }
    /// Get ServerConfig from cached unified Config.
    /// This is a relative expensive operation (clones ServerConfig from R/W locked Config value), it might be deprecated in the future.
    /// TODO: currently throws an error if config does not have a server section
    pub fn get() -> Self {
        common::Config::clone_server()
            .expect("Running server requires config to have server section")
    }
}

// ======================================
// => RPC
// ======================================
// This is the type that implements the generated World trait. It is the business logic
// and is used to start the server.
#[derive(Clone)]
struct HelloServer {
    addr: SocketAddr,
    db: ServerDB,
}

impl HelloServer {
    pub fn new(addr: SocketAddr, db: ServerDB) -> Self {
        Self { addr, db }
    }
}

impl common::rpc::RpcService for HelloServer {
    async fn hello(self, _: Context, name: String) -> String {
        // let sleep_time =
        //     Duration::from_millis(Uniform::new_inclusive(1, 10).unwrap().sample(&mut rand::rng()));
        // tokio::time::sleep(sleep_time).await;
        let msg_count = self.db.messages().unwrap().len();
        format!(
            "Hello, {name}! You are connected from {}. There are {} total messages.",
            self.addr, msg_count,
        )
    }

    // async fn pull_messages(self, context: Context, channel_id: ChannelKey, limit: usize) -> ServerResult<Vec<MessageData>>  {
    //     let data = self.1;
    //     let x = data.db.lock().unwrap();
    //     x.pull_messages(channel_id, limit)
    // }

    // async fn send_message(self, context: Context, channel_id: ChannelKey, user: UserKey, content: String) -> ServerResult<MessageKey>  {
    //     let data = self.1;
    //     let mut x = data.db.lock().unwrap();
    //     x.send_message(channel_id, user, content)
    // }
}

async fn spawn(fut: impl Future<Output = ()> + Send + 'static) {
    tokio::spawn(fut);
}

#[tracing::instrument]
async fn command_server(args: ServerArguments, server: ServerDB) -> anyhow::Result<()> {
    let server_addr = (IpAddr::V6(Ipv6Addr::LOCALHOST), args.port);
    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Json::default).await?;
    tracing::info!("Listening on port {}", listener.local_addr().port());
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(tarpc::server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute. It takes as input any type implementing
        // the generated World trait.
        .map(|channel| {
            let peer_addr = channel.transport().peer_addr().unwrap();
            let server = HelloServer::new(peer_addr, server.clone());
            channel.execute(server.serve()).for_each(spawn)
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    Ok(())
}
